/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_ImageProc */

#ifndef _Included_com_example_test_ImageProc
#define _Included_com_example_test_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_ImageProc
 * Method:    trasformToGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_test_ImageProc_trasformToGray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
